
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    ports:
      - "8000:80"  # Проброс порта 8000 на локальной машине к порту 80 в контейнере

  db:
    image: postgres:latest
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bus_schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Номер порта для доступа к базе данных
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
